#161 Preserve the SRID of allowed area when retrieving it through AccessInfo
geoserver/geofence pull request #162
Opened 2020-12-14 07:26 UTC by taba90

Ensure that the SRID is included in the WKT representation of allowedArea, when the AccessInfo object is built from the rule.

2020-12-14 09:35 UTC, etj requested changes
Are you sure the union will still work ?

https://github.com/geoserver/geofence/blob/master/src/services/core/services-impl/src/main/java/org/geoserver/geofence/services/RuleReaderServiceImpl.java#L210

2020-12-15 08:29 UTC, taba90 commented
thanks for your review @etj. the necessary logic needed for avoid issue on operation between geometry with different SRID has been added. New test are available and the modification has been lively tested with H2 and PostGIS

2020-12-18 10:34 UTC, etj requested changes

2020-12-18 10:34 UTC, etj commented on src/services/core/services-impl/src/test/java/org/geoserver/geofence/services/RuleAdminServiceImplTest.java
> +import org.locationtech.jts.io.WKTReader;
Added unused imports

2020-12-18 13:24 UTC, taba90 commented on src/services/core/services-impl/src/test/java/org/geoserver/geofence/services/RuleAdminServiceImplTest.java
> +import org.locationtech.jts.io.WKTReader;
fixed

2020-12-18 17:13 UTC, etj requested changes
Also handle REST logic, e.g.:

https://github.com/geoserver/geofence/blob/3.4.x/src/services/modules/rest/impl/src/main/java/org/geoserver/geofence/services/rest/impl/RESTRuleServiceImpl.java#L257-L269

2020-12-21 09:02 UTC, taba90 commented
fixed

2021-01-22 15:49 UTC, merged