#163 Clip allowed area filter
geoserver/geofence pull request #164
Opened 2020-12-16 08:33 UTC by taba90

Add the possibility to configure the allowedArea filter as a Intersecting filter or as a Clip filter:

- new Enum SpatialFilterType;
- new fieldSpatialFilterType in model objects;
- necessary logic to display a comboBox with the two values (INTERSECTS, CLIP) in the ruleLimits editor and in the layerDetails editor

2020-12-23 17:23 UTC, etj requested changes
Pls check comments in the code.

2020-12-28 14:51 UTC, taba90 commented on src/services/core/services-impl/src/main/java/org/geoserver/geofence/services/RuleReaderServiceImpl.java
> +                    ret.setSpatialFilterType(SpatialFilterType.INTERSECTS);
fixed

2020-12-28 14:51 UTC, taba90 commented on src/services/core/model/src/main/java/org/geoserver/geofence/core/model/enums/SpatialFilterType.java
> +    INTERSECTS,CLIP
fixed

2020-12-28 14:51 UTC, taba90 commented on src/services/core/persistence/src/test/java/org/geoserver/geofence/core/dao/RuleDAOTest.java
> +import org.geoserver.geofence.core.model.*;
fixed

2020-12-28 14:52 UTC, taba90 commented on src/services/modules/rest/impl/src/main/java/org/geoserver/geofence/services/rest/impl/RESTAdminRuleServiceImpl.java
> +        rule.setWorkspace(in.getWorkspace());
fixed

2020-12-28 14:52 UTC, taba90 commented on doc/setup/sql/002_create_schema_oracle.sql
> +        spatial_filter_type varchar2(255,char),
defenetively too many :)
fixed

2020-12-28 14:52 UTC, taba90 commented on src/services/core/services-impl/src/main/java/org/geoserver/geofence/services/util/AccessInfoInternal.java
> +
fixed

2021-01-22 16:48 UTC, merged